version: '3'

networks:
  webapp_db_network:
    external: true
    
services:
  web:
    image: mlflops/docker_web:1.0
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URI=mysql://root:bmsmlops123@db/database

  db:
    image: mlflops/database_container:2
    environment:
      MYSQL_ROOT_PASSWORD: bmsmlops123
      MYSQL_DATABASE: user_database

networks:
  default:
    external:
      name: webapp_db_network
